#!/usr/bin/env bash
# Installs Nginx and configures it to display "Holberton School for the win!"

apt-get update -y > /dev/null 2>&1
apt-get install nginx -y > /dev/null 2>&1

# Create custom index.html
echo "Holberton School for the win!" > /var/www/html/index.html

sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default

# Ensure Nginx is started using service (not systemctl)
service nginx restart
