#!/usr/bin/env bash
# Installs Nginx and configures it to display "Holberton School for the win!"

apt-get update -y
apt-get install nginx -y

# Create custom index.html
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

# Ensure Nginx is started using service (not systemctl)
service nginx restart
