#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to another page

apt-get update -y
apt-get install nginx -y

# Create the redirection in the default site config
sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
