#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to another page

# Update and install Nginx
apt-get update -y
apt-get install -y nginx

# Add the redirect configuration
sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx using service (systemctl not allowed)
service nginx restart
