#!/usr/bin/env bash
# Configures Nginx to have a custom 404 page containing "Ceci n'est pas une page"

apt-get update -y
apt-get install nginx -y

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Update default nginx config to use the new 404 page
sed -i '/server_name _;/a \\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
